[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
cursive = "0.21.1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"